// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xDfSMb87VGb2TNgY4fHuL0gw96rNSD8',
    appId: '1:704285730328:web:e8ae94fe1a206ab448c56d',
    messagingSenderId: '704285730328',
    projectId: 'flutter-a581b',
    authDomain: 'flutter-a581b.firebaseapp.com',
    storageBucket: 'flutter-a581b.appspot.com',
    measurementId: 'G-QEPR1N5XLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1pvvA2J2flDbbqbHW6dPZFwhAp0ZVPNc',
    appId: '1:704285730328:android:9d158c271ed75d8748c56d',
    messagingSenderId: '704285730328',
    projectId: 'flutter-a581b',
    storageBucket: 'flutter-a581b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJQuMvV1vdV4-vsH4RyXMN-QxDgEnXHs',
    appId: '1:704285730328:ios:2935b0c4b791166048c56d',
    messagingSenderId: '704285730328',
    projectId: 'flutter-a581b',
    storageBucket: 'flutter-a581b.appspot.com',
    iosClientId: '704285730328-qd8ek221nlgs787ei76t5hbqdctctfti.apps.googleusercontent.com',
    iosBundleId: 'com.example.stasLearning1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJQuMvV1vdV4-vsH4RyXMN-QxDgEnXHs',
    appId: '1:704285730328:ios:319a72fb960e1c2348c56d',
    messagingSenderId: '704285730328',
    projectId: 'flutter-a581b',
    storageBucket: 'flutter-a581b.appspot.com',
    iosClientId: '704285730328-gt04b1ooi9crg2p7gps8qp5fo4g2ajip.apps.googleusercontent.com',
    iosBundleId: 'com.example.stasLearning1.RunnerTests',
  );
}
